security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: app_home
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/rh, roles: ROLE_RH }
        - { path: ^/candidat, roles: ROLE_CANDIDAT }
        - { path: ^/register/candidat, roles: ROLE_CANDIDAT }

        - { path: ^/employe, roles: ROLE_EMPLOYE }
        - { path: ^/dashboard, roles: [ROLE_CANDIDAT, ROLE_EMPLOYE, ROLE_RH] }
        - { path: ^/, roles: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_RH: [ROLE_USER, ROLE_CANDIDAT, ROLE_EMPLOYE]
