# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    cv_directory: '%kernel.project_dir%/public/uploads/cv'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\BlockchainService:
        arguments:
            $apiKey:  '%env(ALCHEMY_API_KEY)%'
            $network: '%env(ALCHEMY_NETWORK)%'

    App\Service\CertificatService:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Service\CvAnalysisService:
        arguments:
            $groqApiKey:  '%env(GROQ_API_KEY)%'
            $cvDirectory: '%cv_directory%'
            $nlpApiUrl:   '%env(NLP_API_URL)%'

    App\Security\CertificatVoter:
        tags: ['security.voter']
